name: GH-Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Collect Pages
        run: mkdir -p ./public && cp -r ./jslib ./public/jslib && cp -r ./servers ./public/servers && cp ./index.html ./public/ && cp ./main.js ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
